# TODO config.go 解析配置有 bug，不能同一行写注释，否则会无法解析
bind 0.0.0.0
port 6379
databases 16
# 开启 aof
appendonly yes
appendfilename appendonly.aof

# 当前节点的 ID
self 127.0.0.1:6379
# 集群中所有节点的 ID 列表
peers 127.0.0.1:6380
# peers 127.0.0.1:6379,127.0.0.1:6381